### ISSUE TITLE
Not working with Angular 5.0

### ISSUE THREAD

**Issue by aissam-ahbar** [gmostert/ng2-breadcrumb#93]
Hi guys, 

I upgraded my project from Angular 4.4.5 to 5.0.0 and ng2-breadcrumb is the only component rising an issue on my side. 

Here is my setup:
npm 5.4.2
angular/cli: 1.5.0
ng2-breadcrumb: 0.5.14

Here is the error message: 
```
ERROR in TypeError: staticSymbol.assertNoMembers is not a function
    at AotSummaryResolver.resolveSummary (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:31928:22)
    at CompileMetadataResolver._loadSummary (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:14709:66)
    at CompileMetadataResolver.isDirective (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15003:23)
    at CompileMetadataResolver._getTypeDescriptor (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15269:18)
    at angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15131:78
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15114:49)
    at visitLazyRoute (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:29937:104)
    at AotCompiler.listLazyRoutes (angular5-app/node_modules/@angular/compiler/bundles/compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (angular5-app/node_modules/@angular/compiler-cli/src/transformers/program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (angular5-app/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (angular5-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (angular5-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:542:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.
```

If I uninstall the dependency and remove the breadcrumb from my HTML, the project is working fine.

Any idea?

**Comment by aissam-ahbar** [comment]
A pull request with a new ng5-breadcrumb has been provided.

**Comment by aissam-ahbar** [comment]
At the moment, I am using the following breadcrumb that is fully working:
https://www.npmjs.com/package/ng5-breadcrumb
